### ISSUE TITLE
Package für Backend wird nur auf PR ausgelöst, wenn im Backend-Directory sich was verändert

### ISSUE THREAD

**Issue by Nexusmeister** [Nexusmeister/EnvCalc#51]
Aktuell wird bei jeder PR auf Main der Package Workflow gestartet

Du kannst das mit dem Spezifizieren eines Pfades auf der PR verhindern -> 

![image](https://user-images.githubusercontent.com/37147173/120906483-11079d00-c65a-11eb-9b8d-a16653a0ad43.png)

**Comment by Nexusmeister** [comment]
@crystalcase FYI

**Comment by crystalcase** [comment]
Edited
